### ISSUE TITLE
Distributed samples

### ISSUE THREAD

**Issue by JuanPalacios** [uber/cadence-java-samples#27]
Hello, 

It would be nice to have distributed examples with java because it is the normal case in production environment, with loose coupling between workers activities, workers workflows, starters and the cadence service. One basic example that demontrate this capability should be nice. Currently all the samples are running in the same main method so it is not clear how to distribute the cadence components.

Thanks

**Comment by SriMouli** [comment]
+1

**Comment by ibarrajo** [comment]
Hi, we have an example of a [trip booking saga](https://github.com/berndruecker/trip-booking-saga-java). The saga pattern is a well known [distributed computing architecture](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/saga/saga).

You can find the cadence example here:
https://github.com/uber/cadence-java-samples/tree/master/src/main/java/com/uber/cadence/samples/bookingsaga
