### ISSUE TITLE
worker.wait() is throwing java.lang.IllegalMonitorStateException

### ISSUE THREAD

**Issue by rajeshbr** [uber/cadence-java-samples#6]
https://github.com/uber/cadence-java-samples/blob/e86ff27cd109b87938bd81ded00d1e6bbf12961c/src/main/java/com/uber/cadence/samples/hello/HelloSignal.java#L107

Commenting it out is allowing program to run properly, I think!

**Comment by mfateev** [comment]
Thanks for pointing it out. This line certainly shouldn't be there.

**Comment by mfateev** [comment]
Fixed by https://github.com/uber/cadence-java-samples/pull/9
